### PR TITLE
flush all pending messages

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies

if program terminates before messages are sent by librdkafka they will be lost. `flush` will send all pending messages.

### CODE REVIEW

**Review by pacospace — APPROVED** [review]
lgtm! Thanks! 💯

**Comment by pacospace** [comment]
> lgtm! Thanks!

not sure why mypy is unhappy @KPostOffice

**Comment by KPostOffice** [comment]
Locks like it is a Pipfile.lock issue. I'll relock dependencies

**Pull request merged**
